#!/bin/bash

while read matrix
do
  ID=`echo $matrix | cut -d',' -f1`
  name=`echo $matrix | cut -d',' -f2`

  echo "running for $name with ID: $ID"
  rm -rf $name report."$name"
  ./build/rewrite "$ID" &> report."$name"
done < matrix.ID.name_

